env:
  browser: true
  es6: true

parser: '@typescript-eslint/parser'

extends:
  - plugin:react/recommended
  - airbnb
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/react
  - prettier/@typescript-eslint

plugins:
  - react
  - '@typescript-eslint'
  - prettier

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true

rules:
  max-lines: 1
  import/extensions:
    - 1
    - extensions:
        - '.ts'
        - '.tsx'
  react/jsx-filename-extension:
    - 1
    - extensions:
        - '.tsx'

settings:
  react:
    version: detect
  import/resolver:
      node:
        extensions:
          - '.ts'
          - '.tsx'
